### ISSUE TITLE
1.3.2 and above have link limit

### ISSUE THREAD

**Issue by whitegoldaxe** [edcaron/Reddit-Link-Opener-Firefox#5]
Why is there a new 40 link limit in the two newest versions? I'm having to use v1.3.1 instead for now.

**Comment by edcaron** [comment]
I'll increase the limit on the next version. How much would you like to use ?

**Comment by whitegoldaxe** [comment]
I think reddit maxes out at 100 links per page without third party addons so I guess that would be enough. But why even have a limit? Thanks for the addon by the way it's great.

**Comment by edcaron** [comment]
The limit is to prevent people from setting a giant number of tabs and possibly breaking the browser due to high cpu/memory  usage.

Limit set to 100. You can now update the extension.
