### ISSUE TITLE
Save as bookmarks instead of open?

### ISSUE THREAD

**Issue by Dexnero** [edcaron/Reddit-Link-Opener-Firefox#7]
Hi there,

instead of opening many, many links – is it possible to include an option to just bookmark (perhaps in a special folder of choice) the links? 

I know, it messes up your addon name but I for example scroll through a list of many links and opening them all (100 per 100) and sorting through them later is just insane...

Thanks for the consideration

**Comment by edcaron** [comment]
Hi. Thanks for the tip but i cant do it for now. :disappointed:
