### ISSUE TITLE
Don't record history in private/incognito browsing

### ISSUE THREAD

**Issue by Nadock** [edcaron/Reddit-Link-Opener-Firefox#8]
When opening a link, the URL of the article is added to the user's history. This happens in both regular and private browsing sessions. Firefox doesn't correctly prevent this or clear the history on exit, so there needs to be an additional check for a private browsing session before doing the `addUrl` call.

https://github.com/edcaron/con-reddit-link-opener-firefox/blob/b5368fc7d910cb6177f143a80e86b35de01b70db/background.js#L96

**Comment by edcaron** [comment]
Thank you so much for the tip.

Fixed it. Is now up on 1.3.5. https://addons.mozilla.org/en-US/firefox/addon/con-reddit-link-opener/

**Comment by Nadock** [comment]
Excellent, thanks for the quick work!
